version: "3.9"

networks:
  strapi:
    name: strapi
    external: true
     
services:
  strapicms:
    container_name: strapi
    build:     
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.env:/app/.env
    ports:
      - "1337:1337"
    networks:
      - strapi

