version: "3.9"
services:
  strapi:
    container_name: strapi

    build:
      dockerfile: ${DOCKERFILE}

    restart: unless-stopped
    environment:
      #   DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      #   DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: strapi
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: 123456
      #   JWT_SECRET: ${JWT_SECRET}
      #   ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      ADMIN_JWT_SECRET: tobemodified
      APP_KEYS: "toBeModified1,toBeModified2"
      API_TOKEN_SALT: tobemodified
      TRANSFER_TOKEN_SALT: tobemodified
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    restart: unless-stopped

    image: postgres:14.1-alpine
    environment:     
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data #using a volume
      # - ./data:/var/lib/postgresql/data # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
