name: Publish development
on:
  push:
    branches: [ development ] 
jobs: 
 build:   
    # runs-on: self-hosted
    runs-on: ubuntu-latest  
    steps:
      - name: Print
        run : echo "{{ toJSON(gihub)}}"      
      # - name: Checkout
      #   uses: actions/checkout@v4.0.0
    
      # - name: Run docker compose
      #   run: docker compose --env-file .env.development up -d --build strapi

      