name: Publish development
on:
  push:
    branches: [ development ] 
env:
  DATABASE_USERNAME: admin
jobs: 
 build:   
    runs-on: self-hosted
    # runs-on: ubuntu-latest  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.0.0
    
      - name: Run docker compose
        run: docker compose up -d --build strapi

      