name: Publish development
on:
  push:
    branches: [ development ] 
env:
  DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
  DOCKERFILE_DEV: ${{secrets.DOCKERFILE_DEV}}
jobs: 
 build:   
    runs-on: self-hosted      
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.0.0
    
      - name: Run docker compose
        run: docker compose up -d --build strapi

      