name: Publish main
on:
  push:
    branches: [ main ] 
jobs: 
 build:   
    runs-on: self-hosted
  
    steps:      
      - name: Checkout
        uses: actions/checkout@v4.0.0
             
      - name: Run docker compose
        run: docker compose --env-file .env.production up -d --build strapi

      